### ISSUE TITLE
can not 'pip install' correctly!

### ISSUE THREAD

**Issue by zenghsh3** [dingyaguang117/ACAutomation#1]
beacuse the package don't have the file '_ACAutomation.h', error as follow:
ACAutomation/wrapper.cpp:2:27: fatal error: _ACAutomation.h: No such file or directory
 #include "_ACAutomation.h"
                           ^
compilation terminated.

**Comment by dingyaguang117** [comment]
It's a bug,  I'm trying to fix it.
please download zip package and cd ACAutomation-master, then run "python setup.py install" for now.

**Comment by zenghsh3** [comment]
yeah, i have done this! And your _ACAutomation.h file acquire the header '#include<iostream>' and '#include<string.h>' in my system.

**Comment by dingyaguang117** [comment]
fixed
